#!/bin/bash -e
ROOT="$(realpath $(dirname "$BASH_SOURCE"))"
TMP="$(mktemp -d)"
cp "$ROOT/PKGBUILD" "$TMP"
cd "$TMP"
sed -i "s/md5sums=.*/$(makepkg -g)/" 'PKGBUILD'
ERRORS=$(namcap 'PKGBUILD')
if [ -n "$ERRORS" ]
then
	echo $ERRORS
	exit 1
fi
mkaurball
burp -u 'vinsonchuong' -p "$(pass show archlinux | head -1)" -c 'network' *.src.tar.gz
rm -rf "$TMP"
